install: true
services:
  - docker
script:
  - docker build --tag=exegete46/jekyll:inter -f Dockerfile .
  - export JEKYLL_VERSION=$(docker run --rm exegete46/jekyll:inter jekyll -v | cut -d' ' -f2) 
  - docker build --tag=exegete46/jekyll:$JEKYLL_VERSION  -f Dockerfile .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --tag=exegete46/jekyll:latest -f Dockerfile .;
    docker build --tag=exegete46/jekyll:onbuild -f Dockerfile-onbuild .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push exegete46/jekyll:latest;
    docker push exegete46/jekyll:onbuild;
    docker push exegete46/jekyll:$JEKYLL_VERSION;
    fi